"""Formulaic boundary receipts for enumerated N requests."""
from __future__ import annotations

from typing import Any

REQUEST_TAIL_BITS = 16
LIE_CONJUGATES = frozenset(
    {
        (0, 0, 0),
        (0, 1, 0),
        (1, 0, 1),
        (1, 1, 1),
    }
)
CIRCLE_F = frozenset({(0, 1, 0), (1, 1, 1)})
CIRCLE_P = frozenset({(0, 0, 0), (1, 0, 1)})


def _swap_lr(state: tuple[int, int, int]) -> tuple[int, int, int]:
    left, center, right = state
    return right, center, left


def _swap_lc(state: tuple[int, int, int]) -> tuple[int, int, int]:
    left, center, right = state
    return center, left, right


def _swap_cr(state: tuple[int, int, int]) -> tuple[int, int, int]:
    left, center, right = state
    return left, right, center


def anneal_to_lie_conjugate(state: tuple[int, int, int]) -> dict[str, Any]:
    """Close one local LCR triad to the L=R plane in at most three swaps."""
    current = state
    trajectory = [state]
    for swap in (_swap_lr, _swap_lc, _swap_cr):
        if current in LIE_CONJUGATES:
            break
        current = swap(current)
        trajectory.append(current)
    return {
        "start": state,
        "final": current,
        "steps": len(trajectory) - 1,
        "trajectory": trajectory,
        "lie_conjugate": current in LIE_CONJUGATES,
    }


def classify_triad(state: tuple[int, int, int]) -> dict[str, Any]:
    """Report geometry and Rule 30 correction as independent local facets."""
    left, center, right = state
    lie_conjugate = state in LIE_CONJUGATES
    correction_fires = center == 1 and right == 0
    return {
        "state": list(state),
        "lie_conjugate": lie_conjugate,
        "correction_fires": correction_fires,
        "geometry_level": 0 if lie_conjugate else 1,
        "emission_level": 2 if correction_fires else 1,
        "rule30_emitted_bit": left ^ (center | right),
    }


def _circle(state: tuple[int, int, int]) -> str:
    return "F" if state in CIRCLE_F else "P"


def _boundary_receipt(triad: tuple[int, int, int]) -> dict[str, Any]:
    annealed = anneal_to_lie_conjugate(triad)
    final = annealed["final"]
    return {
        "state": list(final),
        "circle": _circle(final),
        "anneal_steps": annealed["steps"],
        "trajectory": [list(state) for state in annealed["trajectory"]],
    }


class RequestTailCodec:
    """Decode the fixed local tail emitted when a request enumerates N."""

    def __init__(self, tail_bits: int = REQUEST_TAIL_BITS) -> None:
        if tail_bits < 3:
            raise ValueError("tail_bits must be at least 3")
        self.tail_bits = tail_bits
        self._tail_modulus = 1 << tail_bits

    def decode(self, n: int) -> dict[str, Any]:
        """Emit the request tail and resolve its local boundary receipts."""
        if n < 0:
            raise ValueError("N must be non-negative")
        local_tail = n % self._tail_modulus
        request_cycle = n // self._tail_modulus
        request_tail = format(local_tail, f"0{self.tail_bits}b")
        entry = tuple(int(bit) for bit in request_tail[:3])
        exit_ = tuple(int(bit) for bit in request_tail[-3:])
        head = _boundary_receipt(entry)
        tail = _boundary_receipt(exit_)
        return {
            "status": "resolved",
            "evidence": "enumerated_request_tail_exact",
            "N": n,
            "request_tail_bits": self.tail_bits,
            "request_tail": request_tail,
            "request_cycle": request_cycle,
            "entry_triad": list(entry),
            "exit_triad": list(exit_),
            "head": head,
            "tail": tail,
            "matched": head["circle"] == tail["circle"],
            "arc_type": (
                "closed_arc" if head["circle"] == tail["circle"] else "crossing_arc"
            ),
            "lookup_table_entries": 0,
            "complexity": f"O(1) for fixed {self.tail_bits}-bit request tail",
            "semantic_scope": (
                "Exact boundary framing for the local request token generated by N. "
                "This receipt is not the emitted Rule 30 Nth bit."
            ),
        }
