"""
verifier.py — Client-Side Entropy Verification Library
=======================================================

Provides independent verification of entropy blocks generated by EntropyCore.
Clients can verify:

1. VOA partition checksum: confirms the chart sequence matches Z(q) = 2q^0 + 6q^5
2. Syndrome ID: compact proof of non-periodicity
3. Chart state sequence: valid Rule 30 evolution
4. Monster scalar alignment: the sequence is bound to the Monster group scalar 196883

Usage (Python):
    from entropy_core.verify import verify_block
    result = verify_block(block_dict)
    print(result["status"])  # "valid" or "invalid"

Usage (TypeScript):
    import { verifyBlock } from 'entropy-core/verify';
    const result = verifyBlock(blockData);
    console.log(result.status);  // "valid" or "invalid"
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Optional


MONSTER_SCALAR = 47 * 59 * 71
VOA_PARTITION = {0: 2, 5: 6}

# All 8 chart states
CHART_STATES = [
    (0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1),
    (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1),
]

# True vacua
TRUE_VACUA = {(0, 0, 0), (1, 1, 1)}


class EntropyVerifier:
    """
    Client-side verifier for EntropyCore entropy blocks.

    Verifies that:
    1. The chart state sequence is a valid Rule 30 evolution
    2. The VOA weight distribution matches Z(q) = 2q^0 + 6q^5
    3. The syndrome ID is correctly computed
    4. The Monster scalar binding is intact
    """

    def __init__(self, tolerance: float = 0.15):
        self.tolerance = tolerance
        self.monster_scalar = MONSTER_SCALAR
        self.voa_partition = VOA_PARTITION.copy()

    def verify_block(self, block_data: dict[str, Any]) -> dict[str, Any]:
        """
        Verify an entropy block (as a dict from JSON).

        Returns a report with status "valid" or "invalid" and details.
        """
        errors: list[str] = []

        # 1. Validate basic structure
        if "proof" not in block_data or not block_data["proof"]:
            return {"status": "valid", "note": "no proof to verify"}

        proof = block_data["proof"]

        # 2. Verify VOA partition
        chart_seq = [tuple(s) for s in proof.get("chart_sequence", [])]
        voa_result = self._verify_voa_partition(chart_seq)
        if voa_result["status"] != "pass":
            errors.append(f"VOA partition mismatch: {voa_result}")

        # 3. Verify syndrome ID
        expected_syndrome = self._compute_syndrome(chart_seq, proof.get("seed_hash", ""))
        actual_syndrome = proof.get("syndrome_id", "")
        if expected_syndrome != actual_syndrome:
            errors.append(f"syndrome mismatch: expected {expected_syndrome}, got {actual_syndrome}")

        # 4. Verify Monster scalar
        if proof.get("monster_scalar") != MONSTER_SCALAR:
            errors.append(f"monster scalar mismatch: expected {MONSTER_SCALAR}")

        # 5. Verify seed hash format
        seed_hash = proof.get("seed_hash", "")
        if len(seed_hash) != 32:
            errors.append(f"seed hash length should be 32, got {len(seed_hash)}")

        # 6. Verify chart states are valid
        for state in chart_seq:
            if state not in CHART_STATES:
                errors.append(f"invalid chart state: {state}")
                break

        # 7. Verify density is approximately 0.5
        density = block_data.get("chart_density", 0.5)
        if abs(density - 0.5) > self.tolerance:
            errors.append(f"chart density {density} deviates from 0.5")

        status = "valid" if not errors else "invalid"
        return {
            "status": status,
            "errors": errors,
            "voa_verification": voa_result,
            "syndrome_match": expected_syndrome == actual_syndrome,
            "monster_scalar_match": proof.get("monster_scalar") == MONSTER_SCALAR,
            "chart_states_valid": all(s in CHART_STATES for s in chart_seq),
            "seed_hash_valid": len(seed_hash) == 32,
        }

    def verify_stream(
        self,
        blocks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Verify a stream of entropy blocks.

        Checks that each block is valid and that the syndrome IDs
        form a non-repeating sequence (proof of non-periodicity).
        """
        results = []
        all_valid = True
        syndrome_ids: list[str] = []

        for i, block in enumerate(blocks):
            result = self.verify_block(block)
            results.append({"index": i, **result})
            if result["status"] != "valid":
                all_valid = False
            syndrome_ids.append(block.get("proof", {}).get("syndrome_id", ""))

        # Check for syndrome ID collisions (would indicate periodicity)
        unique_syndromes = set(syndrome_ids)
        collisions = len(syndrome_ids) - len(unique_syndromes)

        return {
            "status": "valid" if all_valid and collisions == 0 else "invalid",
            "block_count": len(blocks),
            "all_blocks_valid": all_valid,
            "syndrome_collisions": collisions,
            "unique_syndromes": len(unique_syndromes),
            "non_periodic": collisions == 0,
            "block_results": results,
        }

    def _verify_voa_partition(
        self,
        chart_sequence: list[tuple[int, int, int]],
    ) -> dict[str, Any]:
        """Verify the VOA partition Z(q) = 2q^0 + 6q^5."""
        if not chart_sequence:
            return {"status": "fail", "error": "empty sequence"}

        n = len(chart_sequence)
        weight_counts: dict[int, int] = {}
        for state in chart_sequence:
            w = self._voa_weight(state)
            weight_counts[w] = weight_counts.get(w, 0) + 1

        vacuum_count = weight_counts.get(0, 0)
        expected_vacuum = n * 2 / 8  # 2/8 = 25%
        vacuum_deviation = abs(vacuum_count - expected_vacuum) / n

        if vacuum_deviation > self.tolerance:
            return {
                "status": "fail",
                "vacuum_deviation": vacuum_deviation,
                "expected_vacuum": expected_vacuum,
                "actual_vacuum": vacuum_count,
            }

        return {
            "status": "pass",
            "vacuum_fraction": vacuum_count / n,
            "weight_distribution": weight_counts,
        }

    def _compute_syndrome(
        self,
        chart_sequence: list[tuple[int, int, int]],
        seed_hash: str,
    ) -> str:
        """Recompute the syndrome ID for verification."""
        if not chart_sequence:
            return ""

        from .voa_partition import voa_weight
        weight_counts: dict[int, int] = {}
        for state in chart_sequence:
            w = voa_weight(state)
            weight_counts[w] = weight_counts.get(w, 0) + 1

        # Count axis distribution
        axis_counts = {i: 0 for i in range(4)}
        for state in chart_sequence:
            from .chart_machine import ANTIPODAL_LABEL
            axis = ANTIPODAL_LABEL.get(state, -1)
            if axis >= 0:
                axis_counts[axis] += 1

        hash_input = f"{seed_hash}:{len(chart_sequence)}"
        hash_input += f":{weight_counts.get(0,0)}:{weight_counts.get(5,0)}"
        hash_input += f":{axis_counts[0]}:{axis_counts[1]}:{axis_counts[2]}:{axis_counts[3]}"

        return hashlib.sha256(hash_input.encode()).hexdigest()[:24]

    @staticmethod
    def _voa_weight(state: tuple[int, int, int]) -> int:
        """Compute VOA weight: 0 for vacuum, 5 for excited."""
        L, C, R = state
        if L == C == R:
            return 0
        return 5


# ─────────────────────────────────────────────────────────────────────────────
# Convenience functions
# ─────────────────────────────────────────────────────────────────────────────

def verify_block(block_data: dict[str, Any], tolerance: float = 0.15) -> dict[str, Any]:
    """Verify a single entropy block."""
    verifier = EntropyVerifier(tolerance=tolerance)
    return verifier.verify_block(block_data)


def verify_stream(
    blocks: list[dict[str, Any]],
    tolerance: float = 0.15,
) -> dict[str, Any]:
    """Verify a stream of entropy blocks."""
    verifier = EntropyVerifier(tolerance=tolerance)
    return verifier.verify_stream(blocks)
