"""Lattice Forge public API.

Lattice Forge is an installable lattice/morphism admissibility engine. It ships
an immutable seed ledger and writes project-local interaction state to an
overlay database.
"""

from .forge import Forge
from .ledger import Ledger, build_seed_database
from .cmplx import CMPLXRuntime, RuntimeBudget, RuntimeReceipt
from .cqe import (
    CQEHypervisor,
    CQECurrentFrame,
    CQELightConeHypervisor,
    CQESidecarMonitor,
    D4Token,
    DiagonalBundleResult,
    HistoricalSheet,
    HypervisorLaunchHandle,
    LCRBoundary,
    LightConeFrame,
    ManagedRibbon,
    PaperBundleMatch,
    PaperDatum,
    PaperSheet,
    ReceiptPortal,
    RibbonReceipt,
    SidecarResult,
    SheetSelection,
    SoftmaxHomologyFrame,
    TermBundleResult,
    launch_hypervisor,
    manage_ribbon,
    match_paper_bundle,
    paper_sheet_from_text,
    rehydrate_negative_lane,
)
from .morphonics import morphonics_model_v0_2, verify_morphonics_model
from .overlay import OverlayStore
from .rule30 import (
    rule30_color_chirality_cipher,
    rule30_dihedral_block_hypervisor,
    rule30_discrete_lagrangian,
    rule30_hypervisor_extension_tape,
    rule30_lagrangian_depth_trace,
    rule30_mandelbrot_boundary_scalar,
    rule30_mandelbrot_field_address,
    rule30_morphon_hardened,
    rule30_moving_frame,
    rule30_nth_bit_expression,
    rule30_oloid_antipodal_winding,
    rule30_oloid_parameterization_scan,
    rule30_oloid_winding_from_n,
    rule30_exit_trajectory,
    rule30_physics_method_stack,
    rule30_proof_obligation_ledger,
    rule30_readout_ribbon_machine,
    rule30_reduced_alphabet_catalog,
    rule30_julia_resolution,
    rule30_sheet_operator,
    rule30_sheet_lift,
    rule30_spinor_oloid_model,
    rule30_symmetry_environment,
    rule30_torsor_functor_term,
    rule30_whole_integer_n_scalar_coverage,
    rule30_vignette_algebra,
    rule30_winding_number_proof,
    verify_rule30_color_chirality_cipher,
    verify_rule30_dihedral_block_hypervisor,
    verify_rule30_discrete_lagrangian,
    verify_rule30_hypervisor_extension_tape,
    verify_rule30_lagrangian_depth_trace,
    verify_rule30_mandelbrot_boundary_scalar,
    verify_rule30_mandelbrot_field_address,
    verify_rule30_morphon,
    verify_rule30_moving_frame,
    verify_rule30_nth_bit_expression,
    verify_rule30_oloid_antipodal_winding,
    verify_rule30_oloid_winding_from_n,
    verify_rule30_exit_trajectory,
    verify_rule30_physics_method_stack,
    verify_rule30_proof_obligation_ledger,
    verify_rule30_readout_ribbon_machine,
    verify_rule30_reduced_alphabet_catalog,
    verify_rule30_julia_resolution,
    verify_rule30_sheet_operator,
    verify_rule30_sheet_lift,
    verify_rule30_spinor_oloid_model,
    verify_rule30_symmetry_environment,
    verify_rule30_torsor_functor_term,
    verify_rule30_whole_integer_n_scalar_coverage,
    verify_rule30_vignette_algebra,
    verify_rule30_winding_number_proof,
)
from .seed import SeedStore
from .terminal_tree import build_terminal_composition_tree

__all__ = [
    "Forge",
    "Ledger",
    "OverlayStore",
    "SeedStore",
    "CQEHypervisor",
    "CQECurrentFrame",
    "CQELightConeHypervisor",
    "CQESidecarMonitor",
    "D4Token",
    "DiagonalBundleResult",
    "HistoricalSheet",
    "HypervisorLaunchHandle",
    "LCRBoundary",
    "LightConeFrame",
    "ManagedRibbon",
    "PaperBundleMatch",
    "PaperDatum",
    "PaperSheet",
    "ReceiptPortal",
    "RibbonReceipt",
    "SidecarResult",
    "SheetSelection",
    "SoftmaxHomologyFrame",
    "TermBundleResult",
    "launch_hypervisor",
    "manage_ribbon",
    "match_paper_bundle",
    "paper_sheet_from_text",
    "rehydrate_negative_lane",
    "CMPLXRuntime",
    "RuntimeBudget",
    "RuntimeReceipt",
    "build_seed_database",
    "build_terminal_composition_tree",
    "morphonics_model_v0_2",
    "verify_morphonics_model",
    "rule30_morphon_hardened",
    "verify_rule30_morphon",
    "rule30_vignette_algebra",
    "verify_rule30_vignette_algebra",
    "rule30_moving_frame",
    "verify_rule30_moving_frame",
    "rule30_color_chirality_cipher",
    "verify_rule30_color_chirality_cipher",
    "rule30_discrete_lagrangian",
    "verify_rule30_discrete_lagrangian",
    "rule30_lagrangian_depth_trace",
    "verify_rule30_lagrangian_depth_trace",
    "rule30_mandelbrot_boundary_scalar",
    "verify_rule30_mandelbrot_boundary_scalar",
    "rule30_reduced_alphabet_catalog",
    "verify_rule30_reduced_alphabet_catalog",
    "rule30_symmetry_environment",
    "verify_rule30_symmetry_environment",
    "rule30_physics_method_stack",
    "verify_rule30_physics_method_stack",
    "rule30_whole_integer_n_scalar_coverage",
    "verify_rule30_whole_integer_n_scalar_coverage",
    "rule30_readout_ribbon_machine",
    "verify_rule30_readout_ribbon_machine",
    "rule30_dihedral_block_hypervisor",
    "verify_rule30_dihedral_block_hypervisor",
    "rule30_hypervisor_extension_tape",
    "verify_rule30_hypervisor_extension_tape",
    "rule30_sheet_operator",
    "verify_rule30_sheet_operator",
    "rule30_mandelbrot_field_address",
    "verify_rule30_mandelbrot_field_address",
    "rule30_exit_trajectory",
    "verify_rule30_exit_trajectory",
    "rule30_sheet_lift",
    "verify_rule30_sheet_lift",
    "rule30_julia_resolution",
    "verify_rule30_julia_resolution",
    "rule30_torsor_functor_term",
    "verify_rule30_torsor_functor_term",
    "rule30_spinor_oloid_model",
    "verify_rule30_spinor_oloid_model",
    "rule30_oloid_winding_from_n",
    "rule30_oloid_antipodal_winding",
    "rule30_oloid_parameterization_scan",
    "verify_rule30_oloid_winding_from_n",
    "verify_rule30_oloid_antipodal_winding",
    "rule30_winding_number_proof",
    "verify_rule30_winding_number_proof",
    "rule30_nth_bit_expression",
    "verify_rule30_nth_bit_expression",
    "rule30_proof_obligation_ledger",
    "verify_rule30_proof_obligation_ledger",
]
try:
    from importlib.metadata import PackageNotFoundError, version

    try:
        __version__ = version("lattice-forge")
    except PackageNotFoundError:
        __version__ = "0.3.0"
except ImportError:
    __version__ = "0.3.0"

# --- PROOF-line surface (merged by curation, v0.4.0) ---
from .cayley_dickson_oloid import (
    CAYLEY_DICKSON_SHEET_PATTERN,
    CayleyDicksonOloidNormalForm,
    cayley_dickson_oloid_normal_form,
    verify_cayley_dickson_oloid_normal_form,
)
from .cmplx_lookup_cache import CmplxLookupCache, LookupReceipt, build_default_cache as build_cmplx_lookup_cache

__all__ = list(__all__) + [
    "CmplxLookupCache",
    "CAYLEY_DICKSON_SHEET_PATTERN",
    "CayleyDicksonOloidNormalForm",
    "cayley_dickson_oloid_normal_form",
    "verify_cayley_dickson_oloid_normal_form",
    "LookupReceipt",
    "build_cmplx_lookup_cache",
]
