"""
Octonion algebra via Cayley-Dickson construction.

The octonions O are the unique 8-dimensional normed division algebra over R.
They are constructed by Cayley-Dickson doubling of the quaternions H, which
are themselves the Cayley-Dickson doubling of C, which doubles R.

Each octonion x is an 8-tuple (x_0, x_1, ..., x_7) where:
- x_0 is the real part
- x_1, ..., x_7 are the seven imaginary units e_1, ..., e_7

The multiplication of two octonions a = (a_0, a_R) and b = (b_0, b_R), where
a_R, b_R are quaternions, is:

    a * b = (a_0 * b_0 - conj(b_R) * a_R, b_R * a_0 + a_R * conj(b_0))

with quaternion multiplication recursively defined the same way over complex
numbers, and complex multiplication standard.

The seven imaginary units' multiplication is encoded by the Fano plane:
seven points, seven lines, each line is an oriented triple (e_i, e_j, e_k)
with e_i * e_j = e_k. The standard convention is:
    (1,2,3), (1,4,5), (1,7,6), (2,4,6), (2,5,7), (3,4,7), (3,6,5)
meaning e_1*e_2 = e_3, etc., with cyclic permutation.

Octonions are non-associative but alternative: any subalgebra generated by
two elements is associative.

This module provides:
- Octonion class with __add__, __sub__, __mul__, __neg__, conjugate, norm
- The eight basis elements: O_ONE, O_E1, ..., O_E7
- Hermitian conjugate (= identity on real part, negation on imaginary)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


# Fano plane multiplication: (i, j, k) means e_i * e_j = e_k.
# Standard convention: triples are (1,2,3), (1,4,5), (1,7,6), (2,4,6),
# (2,5,7), (3,4,7), (3,6,5).
FANO_TRIPLES = (
    (1, 2, 3),
    (1, 4, 5),
    (1, 7, 6),
    (2, 4, 6),
    (2, 5, 7),
    (3, 4, 7),
    (3, 6, 5),
)


def _build_octonion_multiplication_table() -> tuple[tuple[tuple[int, int], ...], ...]:
    """
    Build the 8x8 multiplication table for the basis elements
    {1, e_1, ..., e_7}.

    Each entry is (sign, index) where the product e_i * e_j = sign * e_index.
    For index 0 the result is a real scalar; for index 1..7 it's an imaginary
    unit.

    Rules:
    - 1 * e_i = e_i * 1 = e_i  (index 0 acts as identity)
    - e_i * e_i = -1            (square of any imaginary unit is -1)
    - e_i * e_j follows the Fano plane (oriented): if (i,j,k) is a triple in
      the standard order, e_i * e_j = +e_k. The reverse (j,i,k) gives -e_k.
      Cyclic shifts of a triple preserve the +sign within the cycle.
    """
    # Initialize 8x8 table with placeholders
    table: list[list[tuple[int, int]]] = [
        [(0, 0) for _ in range(8)] for _ in range(8)
    ]
    # Identity row/column
    for i in range(8):
        table[0][i] = (1, i)
        table[i][0] = (1, i)
    # Imaginary units square to -1
    for i in range(1, 8):
        table[i][i] = (-1, 0)
    # Build oriented Fano triples (including cyclic shifts)
    triples_with_sign: dict[tuple[int, int], tuple[int, int]] = {}
    for triple in FANO_TRIPLES:
        a, b, c = triple
        # Cyclic shifts get +sign: (a,b)->c, (b,c)->a, (c,a)->b
        triples_with_sign[(a, b)] = (1, c)
        triples_with_sign[(b, c)] = (1, a)
        triples_with_sign[(c, a)] = (1, b)
        # Reverse order gets -sign: (b,a)->-c, (c,b)->-a, (a,c)->-b
        triples_with_sign[(b, a)] = (-1, c)
        triples_with_sign[(c, b)] = (-1, a)
        triples_with_sign[(a, c)] = (-1, b)
    # Fill the table
    for i in range(1, 8):
        for j in range(1, 8):
            if i == j:
                continue
            if (i, j) in triples_with_sign:
                table[i][j] = triples_with_sign[(i, j)]
            else:
                raise ValueError(f"Missing Fano triple for (e_{i}, e_{j})")
    return tuple(tuple(row) for row in table)


OCTONION_MULTIPLICATION_TABLE = _build_octonion_multiplication_table()


@dataclass(frozen=True)
class Octonion:
    """An octonion x = x_0 + x_1*e_1 + x_2*e_2 + ... + x_7*e_7."""

    components: tuple[float, float, float, float, float, float, float, float]

    @classmethod
    def from_components(cls, components: Iterable[float]) -> "Octonion":
        c = tuple(float(x) for x in components)
        if len(c) != 8:
            raise ValueError(f"Octonion requires 8 components, got {len(c)}")
        return cls(c)

    @classmethod
    def real(cls, x: float) -> "Octonion":
        return cls((float(x), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0))

    @classmethod
    def basis(cls, index: int) -> "Octonion":
        """Return the basis element with given index (0=1, 1..7 = e_1..e_7)."""
        if not 0 <= index < 8:
            raise ValueError(f"basis index must be 0..7, got {index}")
        c = [0.0] * 8
        c[index] = 1.0
        return cls(tuple(c))  # type: ignore[arg-type]

    def __add__(self, other: "Octonion") -> "Octonion":
        return Octonion(tuple(a + b for a, b in zip(self.components, other.components)))  # type: ignore[arg-type]

    def __sub__(self, other: "Octonion") -> "Octonion":
        return Octonion(tuple(a - b for a, b in zip(self.components, other.components)))  # type: ignore[arg-type]

    def __neg__(self) -> "Octonion":
        return Octonion(tuple(-a for a in self.components))  # type: ignore[arg-type]

    def __mul__(self, other: "Octonion | float | int") -> "Octonion":
        if isinstance(other, (int, float)):
            return Octonion(tuple(a * float(other) for a in self.components))  # type: ignore[arg-type]
        # Octonion-octonion product via the precomputed table
        out = [0.0] * 8
        for i in range(8):
            ai = self.components[i]
            if ai == 0.0:
                continue
            for j in range(8):
                bj = other.components[j]
                if bj == 0.0:
                    continue
                sign, idx = OCTONION_MULTIPLICATION_TABLE[i][j]
                out[idx] += sign * ai * bj
        return Octonion(tuple(out))  # type: ignore[arg-type]

    def __rmul__(self, other: float | int) -> "Octonion":
        return self.__mul__(other)

    def conjugate(self) -> "Octonion":
        """Octonionic conjugate: real part fixed, imaginary parts negated."""
        c = self.components
        return Octonion((c[0], -c[1], -c[2], -c[3], -c[4], -c[5], -c[6], -c[7]))

    def norm_squared(self) -> float:
        """|x|^2 = x * conj(x) = sum of squared components."""
        return sum(c * c for c in self.components)

    def norm(self) -> float:
        return self.norm_squared() ** 0.5

    def inverse(self) -> "Octonion":
        n2 = self.norm_squared()
        if n2 == 0.0:
            raise ZeroDivisionError("zero octonion is not invertible")
        return Octonion(
            tuple(c / n2 for c in self.conjugate().components)  # type: ignore[arg-type]
        )

    def real_part(self) -> float:
        return self.components[0]

    def imag_part(self) -> "Octonion":
        return Octonion((0.0, *self.components[1:]))  # type: ignore[arg-type]

    def is_real(self, tol: float = 1e-12) -> bool:
        return all(abs(c) < tol for c in self.components[1:])

    def as_tuple(self) -> tuple[float, ...]:
        return tuple(self.components)

    def to_dict(self) -> dict[str, float | list[float]]:
        return {
            "components": list(self.components),
            "norm_squared": self.norm_squared(),
            "real": self.real_part(),
        }

    def __repr__(self) -> str:
        c = self.components
        if all(abs(x) < 1e-12 for x in c[1:]):
            return f"Octonion({c[0]})"
        terms = [f"{c[0]:.4f}"] if abs(c[0]) > 1e-12 else []
        for i, v in enumerate(c[1:], 1):
            if abs(v) > 1e-12:
                terms.append(f"{v:+.4f}*e_{i}")
        return "Octonion(" + " ".join(terms) + ")"


# Pre-built basis elements
O_ONE = Octonion.basis(0)
O_E1 = Octonion.basis(1)
O_E2 = Octonion.basis(2)
O_E3 = Octonion.basis(3)
O_E4 = Octonion.basis(4)
O_E5 = Octonion.basis(5)
O_E6 = Octonion.basis(6)
O_E7 = Octonion.basis(7)
O_ZERO = Octonion((0.0,) * 8)


def verify_octonion_axioms() -> dict[str, object]:
    """
    Verify the basic octonion algebra axioms hold for the implementation.
    """
    errors: list[str] = []
    # 1 * e_i = e_i
    for i in range(1, 8):
        e = Octonion.basis(i)
        if (O_ONE * e).as_tuple() != e.as_tuple():
            errors.append(f"identity failure: 1 * e_{i} != e_{i}")
    # e_i * e_i = -1
    for i in range(1, 8):
        e = Octonion.basis(i)
        prod = e * e
        if prod.as_tuple() != (-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0):
            errors.append(f"square failure: e_{i}^2 != -1, got {prod}")
    # Fano triples: e_i * e_j = +e_k for (i,j,k) in triple
    for triple in FANO_TRIPLES:
        a, b, c = triple
        prod = Octonion.basis(a) * Octonion.basis(b)
        expected = Octonion.basis(c)
        if prod.as_tuple() != expected.as_tuple():
            errors.append(f"Fano triple failure: e_{a} * e_{b} != e_{c}")
        # Reverse: e_j * e_i = -e_k
        prod_rev = Octonion.basis(b) * Octonion.basis(a)
        expected_neg = -Octonion.basis(c)
        if prod_rev.as_tuple() != expected_neg.as_tuple():
            errors.append(f"Fano reverse failure: e_{b} * e_{a} != -e_{c}")
    # Norm composition: |xy|^2 = |x|^2 |y|^2 (the defining property of normed
    # division algebras — Hurwitz's theorem)
    test_x = Octonion((1.0, 2.0, -1.0, 0.5, 0.0, 1.5, -0.5, 0.25))
    test_y = Octonion((0.5, 1.0, 0.0, -1.5, 2.0, 0.0, 0.5, -1.0))
    xy = test_x * test_y
    norm_check = abs(
        xy.norm_squared() - test_x.norm_squared() * test_y.norm_squared()
    )
    if norm_check > 1e-9:
        errors.append(
            f"norm composition failure: |xy|^2 != |x|^2 |y|^2 (diff {norm_check})"
        )
    # Alternativity: x * (x * y) = (x * x) * y for any y (left alternative)
    lhs = test_x * (test_x * test_y)
    rhs = (test_x * test_x) * test_y
    alt_check = sum(
        (a - b) ** 2 for a, b in zip(lhs.components, rhs.components)
    ) ** 0.5
    if alt_check > 1e-9:
        errors.append(
            f"left alternativity failure: x(xy) != (xx)y (diff {alt_check})"
        )
    return {
        "status": "pass" if not errors else "fail",
        "errors": errors,
        "checks_passed": [
            "identity_action",
            "imaginary_square_minus_one",
            "fano_triples_positive",
            "fano_reverse_negative",
            "norm_composition_hurwitz",
            "left_alternativity",
        ],
    }
