"""Recursive closure engine (recrafted from CQECMPLX-Formal-Suite CQE-PAPER-012/020/022/023).

Proves the closure / S3-action / depth-3-ceiling / light-cone=closure claims that ARE
machine-verifiable in this engine. Claims that are NOT backed by the engine (the
"1->7->49->343 = 400 states" / "343-tile void mega-cluster") are flagged as X — the
closure engine dedups, so from a chart seed it collapses to the S3 orbit, not 400.

Fabrication note: CQE-PAPER-012 uses the SAME false OEIS A033996 knight-CA table as
001/002/003/010. That table is NOT reproduced here; honest knight-graph counts
(n=2..8 -> 0,8,16,25,36,49,64) are NOT A033996. See CQE-PAPER-012 §5.1 (FLAGGED X).
"""

from itertools import product
from functools import reduce

from lattice_forge.axiom_verifiers import (
    recursive_closure,
    triality_project,
    CHART_STATES,
    TRUE_VACUA,
)
from lattice_forge.boundary_complex import (
    swap_lr,
    swap_lc,
    swap_cr,
    anneal_distance,
    correction,
)

# Coordinate permutations as images of positions 0,1,2.
# lr: (L,C,R)->(R,C,L) swaps 0,2  -> (2,1,0)
# lc: (L,C,R)->(C,L,R) swaps 0,1  -> (1,0,2)
# cr: (L,C,R)->(L,R,C) swaps 1,2  -> (0,2,1)
_SWAP_PERMS = {
    "lr": (2, 1, 0),
    "lc": (1, 0, 2),
    "cr": (0, 2, 1),
}


def _compose(p, q):
    """(p o q)[i] = p[q[i]]."""
    return tuple(p[q[i]] for i in range(3))


def _s3_group():
    """Set of distinct coordinate-permutation tuples generated by lr/lc/cr."""
    perms = {_SWAP_PERMS["lr"], _SWAP_PERMS["lc"], _SWAP_PERMS["cr"]}
    changed = True
    while changed:
        changed = False
        for a in list(perms):
            for b in list(perms):
                c = _compose(a, b)
                if c not in perms:
                    perms.add(c)
                    changed = True
    return perms


def verify_s3_action():
    """S3 = boundary transposition algebra (CQE-PAPER-012). Honest version."""
    checks = {}

    # 1. The 3 transpositions generate S3 of order exactly 6.
    checks["s3_order_6"] = (len(_s3_group()) == 6)

    # 2. Vacua are fixed by all transpositions (full-S3 stabilizer, orbit size 1).
    checks["vacua_full_stabilizer"] = all(
        swap_lr(v) == v and swap_lc(v) == v and swap_cr(v) == v for v in TRUE_VACUA
    )

    # 3. S3 preserves Hamming weight, so the 6 off-diagonal states split into two
    #    orbits of size 3: weight-1 {(0,1,0),(1,0,0),(0,0,1)} and
    #    weight-2 {(1,1,0),(1,0,1),(0,1,1)}. (NOT a single orbit of 6.)
    orbits = set()
    for s in CHART_STATES:
        if s in TRUE_VACUA:
            continue
        orb = set()
        stack = [s]
        while stack:
            x = stack.pop()
            if x in orb:
                continue
            orb.add(x)
            for fn in (swap_lr, swap_lc, swap_cr):
                t = fn(x)
                if t not in orb:
                    stack.append(t)
        orbits.add(frozenset(orb))
    sizes = sorted(len(o) for o in orbits)
    checks["off_diagonal_two_orbits_size3"] = (sizes == [3, 3])

    # 4. Wrap protocol LR -> LC -> CR resolves every state to a Lie conjugate
    #    (L==R) in <= 3 steps.
    for s in CHART_STATES:
        if s in TRUE_VACUA:
            continue
        cur = s
        steps = 0
        for fn in (swap_lr, swap_lc, swap_cr):
            cur = fn(cur)
            steps += 1
            if cur[0] == cur[2]:
                break
        if cur[0] != cur[2]:
            checks["wrap_resolves_all"] = False
            break
    else:
        checks["wrap_resolves_all"] = True

    # 5. Tight bound: ALL six non-vacua require anneal_distance == 3 (the S3 graph
    #    from any non-vacuum needs 3 transpositions to reach a vacuum). CQE-PAPER-013
    #    Table 2.2 (claiming (0,0,1)->d=2, (1,1,0)->d=2) is FALSE; honest BFS gives
    #    d=3 for every non-vacuum. FLAGGED X.
    tight = {s for s in CHART_STATES if anneal_distance(s) == 3}
    checks["tight_bound_states"] = (tight == set(CHART_STATES) - TRUE_VACUA)

    all_pass = all(checks.values())
    return {
        "status": "pass" if all_pass else "fail",
        "checks": len(checks),
        "sub_checks": checks,
        "defects": 0 if all_pass else 1,
        "honesty_boundary": (
            "S3 = boundary transposition algebra (order 6). Vacua fixed (orbit 1). "
            "Off-diagonal splits into two weight-orbits of size 3 (NOT one orbit of 6). "
            "LR->LC->CR resolves every state to Lie conjugate in <=3; ALL six non-vacua "
            "have anneal_distance 3 (CQE-PAPER-013 Table 2.2 claiming d=2 for two states "
            "is FALSE - FLAGGED X). The 7 S3 sequences = the 7-fold substitution paths."
        ),
    }


def verify_recursive_closure():
    """TRIALITY.project(TRIALITY) closure (CQE-PAPER-020). Honest version.

    NOTE (FLAGGED X): CQE-PAPER-020 claims the closure produces 1->7->49->343 = 400
    distinct states with a 343-tile void mega-cluster. The engine's triality_project
    applies the 7 sequences to a state; from fixed points it returns copies of itself,
    so recursive_closure DEDUPS and does NOT reach 400. The 343-tile count is a Spectre
    aperiodic-tiling assertion, not an engine closure count. We verify only what holds.
    """
    checks = {}

    # 1. triality_project returns exactly 7 children (7-fold substitution).
    seed = CHART_STATES[2]
    checks["seven_fold"] = (len(triality_project(seed, depth=0)) == 7)

    # 2. Void boundary: at depth >= 3, triality_project returns [state] (identity).
    checks["void_boundary_cap"] = all(
        triality_project(s, depth=3) == [s] for s in CHART_STATES
    )

    # 3. Closure stabilizes at depth 3 (recursive_closure(seed,4)==recursive_closure(seed,3)).
    rc3 = recursive_closure(seed, max_depth=3)
    rc4 = recursive_closure(seed, max_depth=4)
    checks["closure_stabilizes_depth3"] = (len(rc4) == len(rc3))

    # 4. Every state in the closure is reachable within depth 3 (termination).
    checks["terminates_depth3"] = all(
        anneal_distance(s) <= 3 for s in rc3
    )

    all_pass = all(checks.values())
    return {
        "status": "pass" if all_pass else "fail",
        "checks": len(checks),
        "sub_checks": checks,
        "defects": 0 if all_pass else 1,
        "honesty_boundary": (
            "triality_project returns 7 children (7-fold). Void boundary at depth>=3 "
            "(identity). Closure stabilizes at depth 3. FLAGGED X: the '1->7->49->343=400 "
            "distinct states / 343-tile void' claim is NOT produced by this closure engine "
            "(it dedups); that count is a Spectre aperiodic-tiling assertion."
        ),
    }


def verify_recursive_light_cone_closure():
    """Light-cone = recursive closure (CQE-PAPER-023). Honest version."""
    checks = {}

    # 1. Universal depth ceiling = 3 (anneal bound = light-cone depth = closure depth).
    checks["depth_ceiling_3"] = (max(anneal_distance(s) for s in CHART_STATES) == 3)

    # 2. Base = 8-state chart.
    checks["base_is_8"] = (len(CHART_STATES) == 8)

    # 3. Boundary operator = correction (chiral doublet fires, not vacua/Lie conj).
    checks["boundary_is_correction"] = (sum(correction(s) for s in CHART_STATES) == 2)

    # 4. Apex = void: triality_project returns identity at depth>=3 (self-recognition).
    checks["apex_void_identity"] = all(
        triality_project(s, depth=3) == [s] for s in CHART_STATES
    )

    # 5. Closure terminates within depth 3 for all chart states.
    checks["closure_depth3"] = all(anneal_distance(s) <= 3 for s in CHART_STATES)

    all_pass = all(checks.values())
    return {
        "status": "pass" if all_pass else "fail",
        "checks": len(checks),
        "sub_checks": checks,
        "defects": 0 if all_pass else 1,
        "honesty_boundary": (
            "Light-cone = recursive closure: apex=void at depth 3 (triality_project "
            "identity), base=8 chart states, boundary=c(D)=C&!R (2 chiral), universal "
            "ceiling 3. FLAGGED X: the '343-tile mega-cluster void' is a Spectre-tiling "
            "assertion NOT produced by the deduping closure engine."
        ),
    }
