"""
PixelForge Genesis — layered Rule 90 + correction: pictures GENERATED,
not printed.

THE INVERSION
-------------
The linearization identity (rule90_linearization, O2') says the nonlinear
rule is the linear rule plus a local correction. Run forward, that prints
textures. Run BACKWARD, it is a universal generative codec:

    Rule 90 is linear over GF(2):  row(t+1) = L XOR R.
    Therefore, for ANY target image (rows = time steps, per bit-plane):

        correction(t, x) = target(t+1, x) XOR rule90(target(t))(x)

    is exactly computable, locally, cell by cell. Every picture IS
    (seed row + correction field): evolve the seed under Rule 90, XOR the
    correction layer at each step, and the target regenerates EXACTLY.

So no image is a printout: every image — including real photographs —
is generated by the layered rule from its correction DNA. The correction
field is the picture's deviation from the linear law; its density is the
picture's nonlinearity fingerprint (the carry density made image-wide).

GENERATION, NOT PASTING
-----------------------
Because Rule 90 is linear, correction fields SUPERPOSE (XOR) and mask:
  - blend two images' DNA -> a hybrid the rule generates
  - keep an image's corrections but reseed from a request -> a picture
    that locally matches the target's structure yet is genuinely
    generated by the request
  - run past the bottom row with zero corrections -> the picture
    CONTINUES itself: free evolution = video frames from the image's
    own dynamics

Rows are single integers (bitmasks): the whole engine is shifts and XORs.
Stdlib only.
"""
from __future__ import annotations

import hashlib
from typing import Dict, List, Tuple

from PixelForge.picture import Picture

Plane = Tuple[int, int]          # (channel 0..2, bit 7..0)


def _r90(row: int, w: int, mask: int) -> int:
    """One Rule 90 step on a toroidal row held as an int bitmask."""
    left = ((row << 1) | (row >> (w - 1))) & mask
    right = ((row >> 1) | ((row & 1) << (w - 1))) & mask
    return left ^ right


def _plane_rows(pic: Picture, ch: int, bit: int) -> List[int]:
    """Extract one bit-plane as a list of row ints (x = bit position)."""
    rows = []
    for y in range(pic.height):
        r = 0
        base = y * pic.width * 3 + ch
        for x in range(pic.width):
            r |= ((pic.buf[base + x * 3] >> bit) & 1) << x
        rows.append(r)
    return rows


class GenesisField:
    """A picture's generative DNA: per-plane seed + correction field such
    that layered Rule 90 + correction regenerates the picture exactly."""

    def __init__(self, width: int, height: int):
        self.width, self.height = width, height
        self.mask = (1 << width) - 1
        self.seeds: Dict[Plane, int] = {}
        self.corrections: Dict[Plane, List[int]] = {}

    # ── decompose: the local solve ───────────────────────────────────────────
    @classmethod
    def from_picture(cls, pic: Picture) -> "GenesisField":
        g = cls(pic.width, pic.height)
        for ch in range(3):
            for bit in range(8):
                rows = _plane_rows(pic, ch, bit)
                g.seeds[(ch, bit)] = rows[0]
                g.corrections[(ch, bit)] = [
                    rows[y + 1] ^ _r90(rows[y], g.width, g.mask)
                    for y in range(pic.height - 1)
                ]
        return g

    # ── evolve: generation ───────────────────────────────────────────────────
    def _evolve_plane(self, plane: Plane, extra_rows: int = 0,
                      seed_override: int = None) -> List[int]:
        rows = [self.seeds[plane] if seed_override is None else seed_override]
        corr = self.corrections[plane]
        total = self.height - 1 + extra_rows
        for y in range(total):
            nxt = _r90(rows[-1], self.width, self.mask)
            if y < len(corr):
                nxt ^= corr[y]            # the layered local correction
            rows.append(nxt)
        return rows

    def regenerate(self, extra_rows: int = 0, seed_pic: Picture = None) -> Picture:
        """Generate the picture from its DNA. extra_rows continues the
        evolution past the image (free run). seed_pic reseeds every plane
        from another picture's first row — request-generated matching."""
        h = self.height + extra_rows
        out = Picture(self.width, h)
        for ch in range(3):
            for bit in range(8):
                so = None
                if seed_pic is not None:
                    so = _plane_rows(seed_pic, ch, bit)[0]
                rows = self._evolve_plane((ch, bit), extra_rows, so)
                for y in range(h):
                    r = rows[y]
                    base = y * self.width * 3 + ch
                    for x in range(self.width):
                        if (r >> x) & 1:
                            out.buf[base + x * 3] |= (1 << bit)
        return out

    # ── correction-space algebra (linear, so it superposes) ─────────────────
    def blend_xor(self, other: "GenesisField") -> "GenesisField":
        """Superpose two DNAs: XOR seeds and correction fields."""
        if (other.width, other.height) != (self.width, self.height):
            raise ValueError("size mismatch")
        g = GenesisField(self.width, self.height)
        for k in self.seeds:
            g.seeds[k] = self.seeds[k] ^ other.seeds[k]
            g.corrections[k] = [a ^ b for a, b in
                                zip(self.corrections[k], other.corrections[k])]
        return g

    def masked(self, keep_top_bits: int = 4) -> "GenesisField":
        """Keep only the significant planes' corrections (low planes free-run):
        locally matches the image's structure, lets fine detail evolve."""
        g = GenesisField(self.width, self.height)
        for (ch, bit), seed in self.seeds.items():
            g.seeds[(ch, bit)] = seed
            if bit >= 8 - keep_top_bits:
                g.corrections[(ch, bit)] = list(self.corrections[(ch, bit)])
            else:
                g.corrections[(ch, bit)] = [0] * (self.height - 1)
        return g

    # ── the fingerprint ──────────────────────────────────────────────────────
    def density(self) -> Dict[str, float]:
        """Correction density per plane group = the image's nonlinearity
        fingerprint (how far it sits from the linear law)."""
        total_bits = self.width * (self.height - 1)
        per_ch = []
        grand = 0
        for ch in range(3):
            fired = sum(bin(r).count("1")
                        for bit in range(8)
                        for r in self.corrections[(ch, bit)])
            per_ch.append(round(fired / (total_bits * 8), 4))
            grand += fired
        return {"R": per_ch[0], "G": per_ch[1], "B": per_ch[2],
                "total": round(grand / (total_bits * 24), 4)}

    def content_hash(self) -> str:
        h = hashlib.sha256()
        for k in sorted(self.seeds):
            h.update(str(self.seeds[k]).encode())
            for r in self.corrections[k]:
                h.update(r.to_bytes((self.width + 7) // 8, "little"))
        return h.hexdigest()[:16]


def seed_picture_from_request(request: str, width: int, height: int) -> Picture:
    """A deterministic seed sheet derived from a request's bytes — the
    request's first-row DNA for reseeded generation."""
    pic = Picture(width, height)
    digest = b""
    counter = 0
    need = width * 3
    while len(digest) < need:
        digest += hashlib.sha256(f"{request}:{counter}".encode()).digest()
        counter += 1
    for x in range(width):
        pic.set(x, 0, (digest[x * 3], digest[x * 3 + 1], digest[x * 3 + 2]))
    return pic
