"""
PixelForge Metamorph — motion INSIDE correction space.

Video, one level up: instead of translating pixels, the correction DNA
itself moves. Each frame is a full GenesisField (seed + correction field)
regenerated by the layered rule — so every frame IS a generated picture,
the endpoints are hash-exact to the source images, and the in-betweens are
evolutions, not blends.

Two motions:

  MORPH      A -> B by progressive bit substitution in correction space.
             At parameter tau, a deterministic threshold sheet decides which
             correction bits (and seed bits) have switched from A's DNA to
             B's. tau=0 regenerates A exactly; tau=1 regenerates B exactly;
             every intermediate is a valid field the rule evolves. GF(2) has
             no halfway bit — the dissolve schedule IS the interpolation.

  TRANSPORT  one field's corrections rotated in x and shifted in t (torus
             again). The structure moves in generative space; pixel motion
             EMERGES from the evolution coupling rows, instead of being
             imposed on pixels.

Threshold sheets (all deterministic):
  "hash"    granular dissolve (SHA-256 stream per cell)
  "sweep"   left-to-right wavefront
  "evolve"  the substrate schedules its own dissolve: a Rule 90 evolution
            accumulates per-cell switch times — organic wavefronts.

Stdlib only; rows are int bitmasks throughout.
"""
from __future__ import annotations

import hashlib
from typing import Dict, List, Tuple

from PixelForge.genesis import GenesisField, _r90
from PixelForge.picture import Picture
from PixelForge.avi import write_avi


# ─── threshold sheets: who switches when ─────────────────────────────────────

def threshold_sheet(width: int, height: int, mode: str = "evolve",
                    seed: str = "metamorph") -> List[List[int]]:
    """thr[y][x] in 0..255 — the cell switches from A to B when
    tau*255 >= thr[y][x]. Deterministic in (mode, seed, size)."""
    if mode == "sweep":
        return [[(x * 255) // max(1, width - 1) for x in range(width)]
                for _ in range(height)]
    if mode == "hash":
        out, stream, ctr = [], b"", 0
        need = width * height
        while len(stream) < need:
            stream += hashlib.sha256(f"{seed}:{ctr}".encode()).digest()
            ctr += 1
        for y in range(height):
            out.append([stream[y * width + x] for x in range(width)])
        return out
    # "evolve": Rule 90 schedules the dissolve — each cell's threshold is
    # the (scaled) first time the evolution lights it from a seeded row.
    mask = (1 << width) - 1
    h0 = int(hashlib.sha256(seed.encode()).hexdigest(), 16)
    row = h0 & mask or 1
    first = [[-1] * width for _ in range(height)]
    steps = 255
    rows = [row]
    for _ in range(steps):
        rows.append(_r90(rows[-1], width, mask))
    for y in range(height):
        r_acc = 0
        for t, r in enumerate(rows):
            rr = ((r << (y % width)) | (r >> (width - (y % width)))) & mask
            newly = rr & ~r_acc
            r_acc |= rr
            x = 0
            while newly:
                if newly & 1 and first[y][x] < 0:
                    first[y][x] = t
                newly >>= 1
                x += 1
            if r_acc == mask:
                break
        for x in range(width):
            if first[y][x] < 0:
                first[y][x] = steps
    return [[min(255, first[y][x] * 255 // steps) for x in range(width)]
            for y in range(height)]


def _masks_for(thr: List[List[int]], tau: float, width: int) -> List[int]:
    """Per-row int masks of cells that have switched at parameter tau."""
    cut = int(round(tau * 255))
    out = []
    for row in thr:
        m = 0
        for x in range(width):
            if row[x] <= cut:
                m |= 1 << x
        out.append(m)
    return out


# ─── the motions ──────────────────────────────────────────────────────────────

def morph_field(a: GenesisField, b: GenesisField, tau: float,
                thr: List[List[int]]) -> GenesisField:
    """The intermediate DNA at parameter tau: a valid GenesisField whose
    bits are A's where the sheet hasn't switched and B's where it has."""
    if (a.width, a.height) != (b.width, b.height):
        raise ValueError("size mismatch")
    if tau <= 0.0:
        return a
    if tau >= 1.0:
        return b
    masks = _masks_for(thr, tau, a.width)
    g = GenesisField(a.width, a.height)
    for k in a.seeds:
        m0 = masks[0]
        g.seeds[k] = (a.seeds[k] & ~m0) | (b.seeds[k] & m0)
        g.corrections[k] = [
            (ca & ~masks[y + 1]) | (cb & masks[y + 1])
            for y, (ca, cb) in enumerate(zip(a.corrections[k], b.corrections[k]))
        ]
    return g


def transport_field(g: GenesisField, dx: int = 0, dt: int = 0) -> GenesisField:
    """Move the DNA itself: rotate corrections in x, shift them in t
    (toroidal both ways). Pixel motion then EMERGES from evolution."""
    out = GenesisField(g.width, g.height)
    w, mask = g.width, g.mask
    dx %= w

    def rot(r: int) -> int:
        return ((r << dx) | (r >> (w - dx))) & mask if dx else r

    n = g.height - 1
    for k in g.seeds:
        out.seeds[k] = rot(g.seeds[k])
        corr = g.corrections[k]
        out.corrections[k] = [rot(corr[(y - dt) % n]) for y in range(n)] if n else []
    return out


# ─── video synthesis in correction space ─────────────────────────────────────

def morph_video(pic_a: Picture, pic_b: Picture, frames: int = 90,
                fps: int = 30, mode: str = "evolve",
                seed: str = "metamorph",
                drift: Tuple[int, int] = (0, 0)) -> Dict:
    """A -> B entirely in correction space. Endpoint frames regenerate the
    sources hash-exactly; every in-between is a rule-generated picture.
    Optional drift transports the morphing DNA per frame (dx, dt)."""
    ga, gb = GenesisField.from_picture(pic_a), GenesisField.from_picture(pic_b)
    thr = threshold_sheet(pic_a.width, pic_a.height, mode=mode, seed=seed)
    out_frames: List[Picture] = []
    for t in range(frames):
        tau = t / max(1, frames - 1)
        g = morph_field(ga, gb, tau, thr)
        if drift != (0, 0) and 0.0 < tau < 1.0:
            g = transport_field(g, dx=drift[0] * t, dt=drift[1] * t)
        out_frames.append(g.regenerate())
    h = hashlib.sha256()
    for p in out_frames:
        h.update(p.content_hash().encode())
    return {
        "frames": out_frames,
        "video_hash": h.hexdigest()[:16],
        "first_exact": out_frames[0].content_hash() == pic_a.content_hash(),
        "last_exact": out_frames[-1].content_hash() == pic_b.content_hash(),
        "mode": mode,
        "fps": fps,
    }


def transport_video(pic: Picture, frames: int = 60, fps: int = 30,
                    dx_per_frame: int = 2, dt_per_frame: int = 0) -> Dict:
    """One image's DNA in motion: per frame the correction field transports
    and the rule regenerates — structure that propagates, not pixels that
    slide."""
    g0 = GenesisField.from_picture(pic)
    out_frames = [transport_field(g0, dx=dx_per_frame * t,
                                  dt=dt_per_frame * t).regenerate()
                  for t in range(frames)]
    h = hashlib.sha256()
    for p in out_frames:
        h.update(p.content_hash().encode())
    return {"frames": out_frames, "video_hash": h.hexdigest()[:16],
            "first_exact": out_frames[0].content_hash() == pic.content_hash(),
            "fps": fps}


def write_morph_avi(result: Dict, path: str) -> str:
    return write_avi(result["frames"], path, fps=result.get("fps", 30))
