"""CADForge - the CAD-facing Forge product (initialized-wireframe CAD).

Documented in the CADForge+WireBlock promotion slice (2026-06-11) but never
implemented as a module. Built here as a real, importable, stdlib-only builder
matching the documented API:

    from CADForge import CADForgeBuilder
    b = CADForgeBuilder("panel_bracket", name="demo")
    b.tweak("width_mm", 96)
    b.attach("rib", anchor_node="base:n0")
    receipt = b.receipt()

CADForge supplies a legal wireframe family; the user assembles from allowed
attachables instead of drawing arbitrary geometry. WireBlock enforces legality;
`to_solidworks_bas` exports a VBA macro from the receipt (SolidWorks remains the
CAD system). Downstream STEP/STL/BOM/toolpath exporters remain open obligations.
"""
from __future__ import annotations

from WireBlock import WireBlock, WireBlockError  # noqa: F401

# Initialized CAD families (base_template, allowed_attachables, bounded variables).
FAMILIES = {
    "panel_bracket": {
        "base_template": "lattice_2x2",
        "description": "flat bracket panel with attachable ribs/holes",
        "nodes": [{"id": f"base:n{i}", "x": (i % 2), "y": (i // 2)} for i in range(4)],
        "edges": [{"source": "base:n0", "target": "base:n1", "edge_type": "x_step"},
                  {"source": "base:n0", "target": "base:n2", "edge_type": "y_step"}],
        "allowed_attachables": ["rib", "hole", "flange"],
        "variables": {"width_mm": {"min": 20, "max": 400, "default": 96},
                      "thickness_mm": {"min": 1, "max": 20, "default": 4}},
    },
    "enclosure_shell": {
        "base_template": "lattice_2x2x2",
        "description": "box enclosure shell with attachable mounts/vents",
        "nodes": [{"id": f"base:n{i}", "x": (i & 1), "y": (i >> 1) & 1, "z": (i >> 2) & 1}
                  for i in range(8)],
        "edges": [{"source": "base:n0", "target": "base:n1", "edge_type": "x_step"},
                  {"source": "base:n0", "target": "base:n2", "edge_type": "y_step"},
                  {"source": "base:n0", "target": "base:n4", "edge_type": "z_step"}],
        "allowed_attachables": ["mount", "vent", "boss", "lid"],
        "variables": {"size_mm": {"min": 30, "max": 500, "default": 120},
                      "wall_mm": {"min": 1, "max": 12, "default": 3}},
    },
    "metamaterial_tile": {
        "base_template": "lattice_8x8",
        "description": "metamaterial unit tile with octad-face cells",
        "nodes": [{"id": f"base:n{i}", "x": i % 8, "y": i // 8} for i in range(64)],
        "edges": [{"source": "base:n0", "target": "base:n1", "edge_type": "x_step"},
                  {"source": "base:n0", "target": "base:n8", "edge_type": "y_step"}],
        "allowed_attachables": ["octad_cell", "strut", "node_mass"],
        "variables": {"cell_mm": {"min": 1, "max": 50, "default": 10},
                      "strut_mm": {"min": 0.2, "max": 5, "default": 1.0}},
    },
}


class CADForgeBuilder:
    def __init__(self, family: str, name: str = "design"):
        if family not in FAMILIES:
            raise WireBlockError(f"unknown family {family!r}; have {sorted(FAMILIES)}")
        f = FAMILIES[family]
        self.family = family
        self.name = name
        self.wb = WireBlock(f["base_template"], f["nodes"], f["edges"],
                            f["allowed_attachables"], f["variables"])
        self._n = 0

    def tweak(self, var: str, value) -> "CADForgeBuilder":
        self.wb.set_var(var, value)
        return self

    def attach(self, attachable: str, anchor_node: str, template: str | None = None,
               scale: float = 1.0, orientation: str = "external") -> "CADForgeBuilder":
        self.wb.attach(f"att{self._n}", attachable, anchor_node, template, scale, orientation)
        self._n += 1
        return self

    def receipt(self) -> dict:
        r = self.wb.receipt(self.name)
        r["family"] = self.family
        return r


def to_solidworks_bas(receipt: dict) -> str:
    """Export a SolidWorks VBA macro that lays the legal wire skeleton."""
    lines = [
        "Option Explicit",
        "' Generated by CADForge / WireBlock.",
        "' SolidWorks remains the CAD system; this macro imports the legal wire skeleton.",
        "Dim swApp As SldWorks.SldWorks",
        "Dim swModel As SldWorks.ModelDoc2",
        "Sub CADForgeWireBlockImport()",
        "    Set swApp = Application.SldWorks",
        "    Set swModel = swApp.NewPart",
    ]
    pos = {n["id"]: (n.get("x", 0), n.get("y", 0), n.get("z", 0)) for n in receipt["nodes"]}
    for e in receipt["edges"]:
        a, b = pos.get(e["source"], (0, 0, 0)), pos.get(e["target"], (0, 0, 0))
        lines.append(f"    swModel.SketchManager.CreateLine "
                     f"{a[0]/1000.0}, {a[1]/1000.0}, {a[2]/1000.0}, "
                     f"{b[0]/1000.0}, {b[1]/1000.0}, {b[2]/1000.0}")
    lines.append("End Sub")
    return "\n".join(lines)


def verify() -> dict:
    b = CADForgeBuilder("panel_bracket", name="demo_panel_bracket")
    b.tweak("width_mm", 96).attach("rib", anchor_node="base:n0")
    r = b.receipt()
    bas = to_solidworks_bas(r)
    return {"forge": "CADForge", "status": "pass" if r["legal"] else "fail",
            "family": r["family"], "design_id": r["design_id"],
            "attachables": len(r["attachables"]), "solidworks_bas_lines": bas.count("\n") + 1}
